#!/bin/bash

#Make directories 
mkdir -p /srv/pterodactyl/panel
cd /srv/pterodactyl/panel

# Create docker-compose.yml
cat > docker-compose.yml <<EOL
version: '3.8'
x-common:
database:
&db-environment
MYSQL PASSWORD: &db-password "CHANGE_ME"
MYSQL_ROOT_PASSWORD: "CHANGE_ME_TOO"
panel:
&panel-environment
APP_URL: "https://pterodactyl.example.com"
APP TIMEZONE: "UTC"
APP_SERVICE_AUTHOR: "noreply@example.com"
TRUSTED_PROXIES: "*"
mail:
&mail-environment
MAIL FROM: "noreply@example.com"
MAIL DRIVER: "smtp"
MAIL HOST: "mail"
MAIL PORT: "1025"
MAIL USERNAME: ""
MAIL PASSWORD: ""
MAIL ENCRYPTION: "true"
services:
database:
image: maniadb:10.5
restart: always
command: --default-authentication-plugin=mysql_native_password
volumes:
- "/srv/pterodactyl/database:/var/lib/mysql"
environment:
<<: *db-environment
MYSQL DATABASE: "panel"
MYSQL USER: "oterodactyl"
cache:
image: redis: alpine
restart: always
panel:
image: ghcr.io/pterodactyl/panel:latest
restart: always
ports:
- "80:80"
- "443:443"
links:
- database
- cache
volumes:
- "/srv/pterodactyl/var/:/app/var/"
-"/srv/pterodactyl/nginx/:/etc/nginx/http.d/"
- "/srv/pterodactyl/certs/:/etc/letsencrypt/"
- "/srv/pterodactyl/logs/:/app/storage/logs"
environment:
<<: ["panel-environment, mail-environment]
DB_PASSWORD: *db-password
APP_ENV: "production"
APP PENVIRONMENT ONLY: "false"
CACHE_DRIVER: "redis"
SESSION DRIVER: "redis"
QUEUE DRIVER: "redis"
REDIS HOST: "cache"
DB_HOST: "database"
DB_PORT: "3306"
networks:
default:
ipam:
config:
- subnet: 172.20.0.0/16
EOL

#Start the panel
docker-compose up -d

# Create a user for the panel
docker-compose run --rm panel php artisan p:user:make
