#!/bin/bash

# Make directories 
mkdir -p /srv/pterodactyl/panel
cd /srv/pterodactyl/panel

# Create docker-compose.yml
cat > docker-compose.yml <<EOL
version: "3.8"
services:
  database:
    image: mariadb:10.5
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /srv/pterodactyl/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: CHANGE_ME_TOO
      MYSQL_DATABASE: panel
      MYSQL_USER: pterodactyl
      MYSQL_PASSWORD: CHANGE_ME
  cache:
    image: redis:alpine
    restart: always
  panel:
    image: ghcr.io/pterodactyl/panel:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - database
      - cache
    volumes:
      - /srv/pterodactyl/var:/app/var
      - /srv/pterodactyl/nginx:/etc/nginx/http.d
      - /srv/pterodactyl/certs:/etc/letsencrypt
      - /srv/pterodactyl/logs:/app/storage/logs
    environment:
      APP_URL: https://pterodactyl.example.com
      APP_TIMEZONE: UTC
      APP_SERVICE_AUTHOR: noreply@example.com
      TRUSTED_PROXIES: "*"
      MAIL_FROM: noreply@example.com
      MAIL_DRIVER: smtp
      MAIL_HOST: mail
      MAIL_PORT: "1025"
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      MAIL_ENCRYPTION: "true"
      DB_HOST: database
      DB_PORT: "3306"
      DB_PASSWORD: CHANGE_ME
      APP_ENV: production
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis
      REDIS_HOST: cache
networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16
EOL

#Start the panel
docker-compose up -d

# Create a user for the panel
docker-compose run --rm panel php artisan p:user:make
